name: CI

on :
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install node packages, check eslint
      run: |
        npm install
        npm run lint
