name: Eslint Checker

on :
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: npm install
        run: |
          cd ..
          npm i --ignore-scripts
      - name: check eslint
        run: |
          cd ..
          npx eslint src/**/*.js 
