name: CI

on :
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: npm install
        run: |
          cd ..
          npm i --ignore-scripts
        
      - name: ESLint checker
        uses: ninosaurus/eslint-check@v5.3.1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          custom-directory: ./src/
          eslint-config-path: ./
